# Defaults for EC2 configuration.
---
# Common
ec2_region: eu-west-1

# EC2 instance defaults
ec2_ami_id: ami-3907d64e
ec2_instance_type: t1.micro
ec2_assign_public_ip: False
#volumes:
#  - device_name: /dev/xvda
#    volume_size: 20

# Security group defaults
ec2_security_group: sg_dcos
ec2_security_group_name: Security Group for DC/OS

# VPC defaults
vpc_state: present
vpc_cidr_block: 10.0.0.0/16
vpc_resource_tags: { Name: dcos-vpc, "Environment":"Development" }
vpc_subnets:
  - cidr: 10.0.0.0/24
    az: eu-west-1a
    resource_tags: { Name: dcos-subnet-public, "Environment":"Dev", "SubnetType":"Private" }
  - cidr: 10.0.1.0/24
    az: eu-west-1a
    resource_tags: { Name: dcos-subnet-private, "Environment":"Dev", "SubnetType":"Public" }
vpc_route_tables:
  - subnets:
     - 10.0.0.0/24
    routes:
     - dest: 0.0.0.0/0
       gw: igw
  - subnets:
     - 10.0.1.0/24
    routes:
     - dest: 0.0.0.0/0
       gw: igw
vpc_internet_gw: True
