---
go_lang_url: https://storage.googleapis.com/golang/go1.6.linux-amd64.tar.gz
go_download_dir: /tmp/go1.6.linux-amd64.tar.gz

k8s_git_repo: https://github.com/kubernetes/kubernetes
k8s_checkout_dir: /tmp/k8s
