---
- name: Add apt-key
  become: yes
  become_method: sudo
  apt_key: id=E56151BF keyserver=keyserver.ubuntu.com state=present

- name: Add Mesosphere repo
  become: yes
  become_method: sudo
  apt_repository: repo="{{marathon_apt_repo}}" state=present

- name: Install Marathon package
  become: yes
  become_method: sudo
  apt: pkg={{ marathon_apt_package }} state=present update_cache=yes
