---
# EC2 dynamic invetory create different permutations of host collections based on instance properties such as tags.
# See http://codeheaven.io/15-things-you-should-know-about-ansible/ item 12 for more info.
# Install Java on all instances tagged with "java".
- name: Install Java on tagged hosts
  hosts: tag_java
  gather_facts: true
  remote_user: ubuntu
  roles:
    - java

- name: Install Zookeeper on tagged hosts
  hosts: tag_zookeeper
  gather_facts: true
  remote_user: ubuntu
  roles:
    - zookeeper

- name: Install Mesos on tagged hosts
  hosts: tag_mesos_master
  gather_facts: true
  remote_user: ubuntu
  roles:
    - mesos

- name: Install Mesos slaves on tagged hosts
  hosts: tag_mesos_slave
  gather_facts: true
  remote_user: ubuntu
  roles:
    - {role: mesos, mesos_install_mode: "master-slave"}
