---
- name: Wait for SSH
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Wait for SSH
      wait_for:
        host: "{{ hostvars[item].ec2_private_ip_address }}"
        port: 22
        delay: 10
        timeout: 320
        state: started
      with_items: "{{ groups['tag_ansible_managed'] }}"

