---
- name: include distribution specific variables.
  include_vars: "{{ item }}"
  with_items:
  - "{{ ansible_distribution }}/main.yml"
  - "{{ ansible_distribution }}/{{ ansible_distribution_release }}-vars.yml"

- name: perform an apt-get update.
  become: yes
  become_method: sudo
  apt: update_cache=yes

- name: include distribution specific tasks.
  include: "{{ ansible_distribution_release }}-tasks.yml"

- name: add keys
  become: yes
  become_method: sudo
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D

- name: add apt_repository
  become: yes
  become_method: sudo
  apt_repository: repo="{{repository}}"

- name: perform an apt-get update.
  become: yes
  become_method: sudo
  apt: update_cache=yes

