---
- name: Add apt-key
  become: yes
  become_method: sudo
  apt_key: id=E56151BF keyserver=keyserver.ubuntu.com state=present

- name: Add mesosphere repo
  become: yes
  become_method: sudo
  apt_repository: repo='deb {{ mesosphere_apt_url }} {{ansible_distribution_release|lower}} main' state=present

- name: Install Debian OS packages
  become: yes
  become_method: sudo
  apt: pkg={{item}} state=present update_cache=yes
  with_items:
    - wget
    - curl
    - unzip
    - python-setuptools
    - python-dev
    - mesos={{mesos_version}}-{{mesos_package_version}}.{{ansible_distribution|lower}}{{ansible_distribution_version.split('.')|join('')}}
