---

# While waiting for https://github.com/ansible/ansible-modules-core/issues/191
- name: Reload daemon
  become: yes
  become_method: sudo
  command: systemctl daemon-reload
  
# i.e. upgrade mesos, templates stay the same...
- name: Restart mesos-master
  become: yes
  become_method: sudo
  service: name=mesos-master state=restarted
  when: mesos_install_mode == "master" or mesos_install_mode == "master-slave"

- name: Restart mesos-slave 
  become: yes
  become_method: sudo
  service: name=mesos-slave state=restarted
  when: mesos_install_mode == "slave" or mesos_install_mode == "master-slave"
