# Create EC2 instances.
---
- name: Launch EC2 instance(s)
  ec2:
    key_name: "{{ ec2_keypair }}"
    group: "{{ ec2_security_group }}"
    instance_type: "{{ ec2_instance_type }}"
    region: "{{ ec2_region }}"
    image: "{{ ec2_ami_id }}"
    wait: true
    exact_count: "{{ item.exact_count }}"
    count_tag:
      name: "{{ item.count_tag }}"
    instance_tags: "{{ item.tags }}"
  register: ec2
  with_items: "{{ ec2_instances }}"
