# Create security group(s)
---
- name: Create EC2 Security Group
  local_action:
    module: ec2_group
    name: "{{ ec2_security_group }}"
    description: "{{ ec2_security_group_name }}"
    region: "{{ ec2_region }}"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0

      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/0

      - proto: tcp
        from_port: 2181
        to_port: 2181
        cidr_ip: 10.0.0.0/8

      - proto: tcp
        from_port: 2888
        to_port: 2888
        cidr_ip: 10.0.0.0/8

      - proto: tcp
        from_port: 3888
        to_port: 3888
        cidr_ip: 10.0.0.0/8

      - proto: tcp
        from_port: 5050
        to_port: 5050
        cidr_ip: 10.0.0.0/8

      - proto: tcp
        from_port: 5051
        to_port: 5051
        cidr_ip: 10.0.0.0/8

      # Open all tcp ports for 10.0.0.0/8.
      - proto: tcp
        from_port: 0
        to_port: 65535
        cidr_ip: 10.0.0.0/8

      - proto: icmp
        from_port: -1 # icmp type, -1 = any type
        to_port:  -1 # icmp subtype, -1 = any subtype
        cidr_ip: 10.0.0.0/8
