---

- name: Configure AWS VPC
  ec2_vpc:
    state: present
    cidr_block: 172.22.0.0/16
    resource_tags: { Name: dcos-vpc, "Environment":"Development" }
    subnets:
      - cidr: 172.22.1.0/24
        az: "{{ ec2_az1 }}"
        resource_tags: { Name: dcos-subnet, "Environment":"Dev" }
    internet_gateway: True
    route_tables:
      - subnets:
          - 172.22.1.0/24
        routes:
          - dest: 0.0.0.0/0
            gw: igw
    region: "{{ ec2_region }}"
  register: vpc

- set_fact:
    vpc_facts: "{{ vpc }}"

- name: Create Internet GW
  ec2_vpc_igw:
    vpc_id: "{{ vpc.vpc_id }}"
    region: "{{ ec2_region }}"
    state: present
  register: igw

- name: Tagging the new internet gateway created
  ec2_tag:
    resource: "{{ igw.gateway_id }}"
    state: present
    region: "{{ ec2_region }}"
    tags:
      Name: dcos-gateway

