---

- name: Create AWS VPC
  ec2_vpc_net:
    name: dcos-vpc
    cidr_block: 10.0.0.0/16
    region: "{{ ec2_region }}"
    tags: "{{ vpc_resource_tags }}"
    tenancy: default
  register: vpc

- debug: var=vpc verbosity=1

- name: Create VPC public subnet
  ec2_vpc_subnet:
    state: present
    vpc_id: "{{ vpc.vpc.id }}"
    cidr: 10.0.0.0/24
    region: "{{ ec2_region }}"
    resource_tags: { Name: subnet-public }
  register: public_subnet

- debug: var=public_subnet verbosity=1

- name: Create VPC private subnet
  ec2_vpc_subnet:
    state: present
    vpc_id: "{{ vpc.vpc.id }}"
    cidr: 10.0.1.0/24
    region: "{{ ec2_region }}"
    resource_tags: { Name: subnet-private }
  register: private_subnet

- debug: var=private_subnet verbosity=1

- ec2_vpc_subnet_facts:
    region: "{{ ec2_region }}"
    filters:
      vpc-id: "{{ vpc.vpc.id }}"
  register: vpc_subnet_facts

- debug: var=vpc_subnet_facts verbosity=1

- name: Create Internet GW
  ec2_vpc_igw:
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ ec2_region }}"
    state: present
  register: igw

- debug: var=igw verbosity=1

- name: Tagging the new internet gateway created
  ec2_tag:
    resource: "{{ igw.gateway_id }}"
    state: present
    region: "{{ ec2_region }}"
    tags:
      Name: dcos-gateway

- name: Configure private subnet route table
  ec2_vpc_route_table:
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ ec2_region }}"
    tags: { Name: dcos-private-route-table }
    subnets:
      - "{{ private_subnet.subnet.id }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ igw.gateway_id }}"
  register: vpc_private_route_table

- debug: var=vpc_private_route_table verbosity=1

- name: Configure public subnet route table
  ec2_vpc_route_table:
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ ec2_region }}"
    tags: { Name: dcos-public-route-table }
    subnets:
      - "{{ public_subnet.subnet.id }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ igw.gateway_id }}"
  register: vpc_public_route_table

- debug: var=vpc_public_route_table verbosity=1

