---

- name: Install marathon-lb load balancer
  command: dcos package install --yes marathon-lb

- name: Wait a bit for the package install to complete
  pause: seconds=30

- name: Scale the martathon-lb to run on each public agent
  command: dcos marathon app update /marathon-lb instances="{{ groups['tag_dcos_slave_public'] | length }}"

- name: Copy 'options.json' to controller host.
  copy: src=options.json dest=./options.json mode=0440

- name: Set up marathon-lb for internal LB using 'options.json'
  command:  dcos package install --options=./options.json --yes marathon-lb

- name: Copy 'nginx-external.json' to controller host.
  copy: src=nginx-external.json dest=./nginx-external.json mode=0440

- name: Launch external nginx sample application.
  command: dcos marathon app add ./nginx-external.json

- name: Copy 'nginx-internal.json' to controller host.
  copy: src=nginx-internal.json dest=./nginx-internal.json mode=0440

- name: Launch internal nginx sample application.
  command: dcos marathon app add ./nginx-internal.json

- name: Copy 'nginx-everywhere.json' to controller host.
  copy: src=nginx-everywhere.json dest=./nginx-everywhere.json mode=0440

- name: Launch everywhere nginx sample application.
  command: dcos marathon app add ./nginx-everywhere.json

