---
- name: include platform specific variables.
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_release }}-vars.yml"

- name: include platform specific tasks.
  include: "{{ ansible_distribution }}-{{ ansible_distribution_release }}-tasks.yml"

#- name: install required applications
#  become: yes
#  become_method: sudo
#  apt: name={{item}} update_cache=yes state=latest
#  with_items:
#    - "{{ required_apps }}"

- name: add keys
  become: yes
  become_method: sudo
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D

- name: add apt_repository
  become: yes
  become_method: sudo
  apt_repository: repo="{{repository}}"

#- name: add linux-image-extra package (for aufs storage driver)
#  become: yes
#  become_method: sudo
#  apt: name=linux-image-extra-{{ansible_kernel}} state=latest

- name: add apparmor
  become: yes
  become_method: sudo
  apt: name=apparmor update_cache=yes state=latest
  when: install_apparmor == true

- name: add docker-engine
  become: yes
  become_method: sudo
  apt: name=docker-engine update_cache=yes state=latest

- name: start docker service
  become: yes
  become_method: sudo
  service: name=docker state=started

- name: install pip
  become: yes
  become_method: sudo
  apt: name={{item}} update_cache=yes state=latest
  with_items:
  - python-pip
  - python-dev
  - build-essential

- name: install docker-py
  become: yes
  become_method: sudo
  pip: name=docker-py state=latest

