---
#- name: include platform specific variables.
#  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_release }}-vars.yml"

- name: include platform specific tasks & variables.
  include: "{{ ansible_distribution }}/main.yml"

- name: add apparmor
  become: yes
  become_method: sudo
  package: name=apparmor state=latest
  when: install_apparmor == true

- name: add docker-engine
  become: yes
  become_method: sudo
  package: name=docker-engine state=latest
  
- name: start docker service
  become: yes
  become_method: sudo
  service:
    name=docker
    state=started

# Configure the storage driver for Docker, see https://docs.docker.com/engine/userguide/storagedriver/imagesandcontainers/
# for more information.
- name: configure docker storage driver
  become: yes
  become_method: sudo
  lineinfile:
    dest=/lib/systemd/system/docker.service
    regexp="^ExecStart=/usr/bin/dockerd .*$"
    line="ExecStart=/usr/bin/dockerd -H fd:// -s {{ storage_driver }}"
  notify:
  - reload systemd
  - restart docker

- name: install pip
  become: yes
  become_method: sudo
  package: name={{item}} state=latest
  with_items: "{{ pip_packages }}"
#  - python-pip
#  - "{{ python_development }}"
#  - build-essential

- name: install docker-py
  become: yes
  become_method: sudo
  pip: name=docker-py state=latest

