---

- name: Install required software (uznip, ipset etc.)
  become: yes
  become_method: sudo
  apt: name={{item}} update_cache=yes state=latest
  with_items:
  - unzip
  - ipset
  - selinux-utils

- name: Create temporary DCOS dirctory
  file: path="{{dcos_temp_dir}}" state=directory

- name: Download DCOS installer
  get_url: url={{bootstrap_url}} dest={{dcos_temp_dir}}/{{bootstrap_script}}

- name: Make {{bootstrap_script}} executable
  file: path={{dcos_temp_dir}}/{{bootstrap_script}} state=touch mode=0700

- name: Run the DCOS installer
  become: yes
  become_method: sudo
  shell: bash {{dcos_temp_dir}}/{{bootstrap_script}} master

