---

- name: Install required software (uznip, ipset etc.)
  become: yes
  become_method: sudo
  apt: name={{item}} update_cache=yes state=latest
  with_items:
  - unzip
  - ipset
  - selinux-utils

- name: Create temporary DCOS dirctory
  file: path="{{dcos_temp_dir}}" state=directory

- name: Download DCOS installer
  get_url: url={{bootstrap_url}} dest={{dcos_temp_dir}}/{{bootstrap_script}}

- name: Make {{bootstrap_script}} executable
  file: path={{dcos_temp_dir}}/{{bootstrap_script}} state=touch mode=0700

- name: Create symbolic links needed by the installer
  become: yes
  become_method: sudo
  file: src={{ item.src }} dest={{ item.dest }} state=link
  with_items:
    - { src: '/bin/mkdir', dest: '/usr/bin/mkdir' }
    - { src: '/bin/ln', dest: '/usr/bin/ln' }
    - { src: '/bin/tar', dest: '/usr/bin/tar' }
    - { src: '/bin/rm', dest: '/usr/bin/rm' }
    - { src: '/usr/sbin/useradd', dest: '/sbin/useradd' }

- name: Run the DCOS installer
  become: yes
  become_method: sudo
  shell: bash {{dcos_temp_dir}}/{{bootstrap_script}} master

